### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by Giounona** [andreaazzini/segnet#12]
Hi @andreaazzini I'm trying to use your code and I'm getting issues related to the Queue Shuffling during training.

Do you know what should I do to proceed?
```
OutOfRangeError (see above for traceback): RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 12, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

```

**Comment by andreaazzini** [comment]
Hi @Giounona, have you used `tfrecorder.py` to prepare your `TFRecords` files?
If so, what is the size of your input images? The network currently works only for 224x224 images.

**Comment by Giounona** [comment]
@andreaazzini  thanks for the reply.  Yes I have used tfrecorder.py. Indeed the size of my images was not 224x224 so I resized them and repeated the experiment. However I got the same error


```
OutOfRangeError (see above for traceback): RandomShuffleQueue '_3_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 12, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]


```

**Comment by andreaazzini** [comment]
Have you followed the instructions in the README correctly?

- Specify your working dataset name in `config.py`
- Configure the segmentation label colors in `config.py`
- Use `tfrecorder.py` to generate the TFRecords, which need to be placed in the `input/your-working-dataset` folder

**Comment by dlahmad** [comment]
I have done as you said and the same problem. Basically i have my pictures as jpg. The are scaled to 224 * 224 * 3.  I put them in the /input/raw/train for the images and the /input/raw/train-labels for the masks. For example for an image **00001.jpg** it looks like this:

- image file: /input/raw/train/00001.jpg
- mask files: /input/raw/train-labels/00001.jpg

with this setup i use tfrecorder and create tfrecord files and but them in a folder **testset**.
My config file looks like this:
autoencoder = 'segnet'

> colors = {
>   'testset': [
>     [255, 255, 255],   # Part
>     [0, 0, 0] # Background
>   ]
> }
> gpu_memory_fraction = 0.7
> strided = True
> working_dataset = 'testset'

The mask file has the two colors. For testing the code i just added 36 train images.

Still it is not working and i get the error. Do you have a clue what the problem is?

Best regards

**Comment by andreaazzini** [comment]
@Vedaevolution JPEG is still not supported by `tfrecorder.py`. I suggest you to convert all your JPEG files into PNG. You could use `mogrify` to do the job.

```
mogrify -format png ./*.jpeg
```
