### ISSUE TITLE
input and dataset

### ISSUE THREAD

**Issue by Shathe** [andreaazzini/segnet#8]
Hi,

I just found your project. Actually, it looks pretty cool/good.

I have some questions to ask you. One of them is if you could show me the structure of your input folder. 
Another one is related to that folder too. I really can't find the segnet-32 dataset, do you still have it? or do you have any dataset avaidable?

I've also seen you've been updating your projecto to tensorflow v1.0. Is the proyect fully updated or at least does the current version work fine?

I would be very gratefull if you could help me.

Thanks!

**Comment by andreaazzini** [comment]
Hi Shathe,

The `input` folder contains a subfolder for each dataset you want to work with. Suppose you have two datasets: `segnet-13` and `segnet-32`. Your input folder would look like this:

```
input/
    segnet-13/
        train.tfrecords
        train_labels.tfrecords
        test.tfrecords
        test_labels.tfrecords
    segnet-32/
        train.tfrecords
        train_labels.tfrecords
        test.tfrecords
        test_labels.tfrecords
```

The TFRecords are generated with the `tfrecorder.py` script. If you want to use the default settings, put your PNG images in a `raw` folder, as follows:

```
input/
    raw/
        train/
        train-labels/
        test/
        test-labels/
```

More specifically, `train/`, `train-labels/`, `test/` and `test-labels/` contain your PNG images to be converted by `tfrecorder.py`.

About segnet-32, I think you can find it [here](https://github.com/alexgkendall/SegNet-Tutorial), in the `CamVid` folder. It requires a little bit of work to transform the labels, though. [Email me](mailto:and.azzini@gmail.com) so that I can send you my version of the dataset if I find it.

This version should work fine on TensorFlow 1.0.

**Comment by Shathe** [comment]
Thanks a lot! I didn't know about the tfrecorder.py generator.  I really appreaciate it!

**Comment by gspell** [comment]
What sort of transforming is needed for the image annotations before using the tfrecorder to convert them? Does it involve putting the annotated images (labels) into the color-map that you have in your config.py file?

Thanks!!
